workflows:
  version: 2
  spin-worker:
    jobs:
      setup-aws:
        docker:
          - image: kalaytan/alpine_awscli
        context: AWS-pav-personal-account
        steps:
          - checkout
          - run:
              name: Show aws access key
              command: echo "$AWS_ACCESS_KEY_ID"
          - run:
              name: Print the Current Time
              command: date

